#define TORSO_WIDTH 1.3
#define TORSO_HEIGHT TORSO_WIDTH * 0.2
#define TORSO_DEPTH TORSO_WIDTH * 0.9

#define NECK_HEIGHT (TORSO_HEIGHT) * 0.75
#define SHOULDER_HEIGHT TORSO_HEIGHT * 0.5
#define THIGHS_HEIGHT TORSO_HEIGHT * 0.65

#define FEET_HEIGHT TORSO_HEIGHT * 0.6

#define JOINT_SIZE 0.05

#define HEAD_WIDTH TORSO_WIDTH * 0.15

#define TRUNK_HEIGHT TORSO_WIDTH * 0.8

#define TAIL_WIDTH TORSO_WIDTH * 0.2
#define TAIL_HEIGHT TORSO_WIDTH * 0.4
#define ELEPHANT_HEIGHT (TORSO_HEIGHT + THIGHS_HEIGHT + FEET_HEIGHT)
