#define TORSO_WIDTH 0.5
#define TORSO_HEIGHT TORSO_WIDTH * 0.70
#define TORSO_DEPTH TORSO_WIDTH * 0.60

#define SHOULDER_HEIGHT TORSO_HEIGHT / 2
#define THIGHS_HEIGHT TORSO_HEIGHT * 0.65

#define FEET_HEIGHT TORSO_HEIGHT * 0.6

#define JOINT_SIZE 0.05

#define HEAD_WIDTH TORSO_WIDTH * 0.5

#define TRUNK_HEIGHT TORSO_WIDTH * 0.8

#define TAIL_WIDTH TORSO_WIDTH * 0.2
#define TAIL_HEIGHT TORSO_WIDTH * 0.4
#define ELEPHANT_HEIGHT (TORSO_HEIGHT + THIGHS_HEIGHT + FEET_HEIGHT)
